### ISSUE TITLE
Todos not found

### ISSUE THREAD

**Issue by Siddhant2016** [iamshaunjp/node-js-playlist#5]
I've followed your tutorial properly and wrote the code as instructed by you but I get this error saying todos is not defined. 
`ReferenceError: /media/legend/New Volume/Projects/Web Projects/ChatBox/views/todo.ejs:26
    24| 		</form>
    25| 		<ul>
 >> 26| 			<% for(var i=0; i < todos.length; i++){ %>
    27| 			<li><%= todos[i].item %></li>
    28| 			<% } %>
    29| 		</ul>

todos is not defined
    at eval (eval at compile (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:20:25)
    at returnedFn (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/ejs/lib/ejs.js:555:17)
    at tryHandleCache (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/ejs/lib/ejs.js:203:34)
    at View.exports.renderFile [as engine] (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/ejs/lib/ejs.js:412:10)
    at View.render (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/view.js:128:8)
    at tryRender (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/application.js:640:10)
    at Function.render (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/response.js:971:7)
    at /media/legend/New Volume/Projects/Web Projects/ChatBox/routes/routes.js:27:7
    at Layer.handle [as handle_request] (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/layer.js:95:5)
    at next (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/route.js:137:13)
    at securePages (/media/legend/New Volume/Projects/Web Projects/ChatBox/routes/routes.js:10:4)
    at Layer.handle [as handle_request] (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/layer.js:95:5)
    at next (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/layer.js:95:5)
    at /media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/index.js:335:12)
    at next (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/index.js:174:3)
    at router (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/media/legend/New Volume/Projects/Web Projects/ChatBox/node_modules/express/lib/router/layer.js:95:5)`

PS: By the tutorial number 34, you haven't included the "todo-list.js" file. How is your code working properly even after that? How are the requests handled even when the file for jQuery are not included

**Comment by hmake98** [comment]
look like, you have not define todos in **todoController.js** file. 
define the todos in the file.

```
module.exports = function(app){
  app.get('/', function(req, res){
    res.render('todo', {todos: data});
  }); 

```

**Comment by bhaskar253** [comment]
Can someone close this issue as I think @hmake98 provided the correct info.
